name: CI + Deploy Frontend & Backend

on:
  push:
    branches: ["master"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore /p:TreatWarningsAsErrors=false

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

      - name: Check code formatting
        run: dotnet format --verify-no-changes || echo "Code formatting differences found"

      - name: Read secret
        run: echo "Secret value is ${{ secrets.MY_SECRET }}"

      - name: Simulated deploy
        run: bash ./deploy.sh

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Upload frontend artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'frontend'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
